// Code generated by go-swagger; DO NOT EDIT.

package ip_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"golang.org/x/net/context"
)

// NewPostSysbusNMCGetWANStatusParams creates a new PostSysbusNMCGetWANStatusParams object
// with the default values initialized.
func NewPostSysbusNMCGetWANStatusParams() *PostSysbusNMCGetWANStatusParams {

	return &PostSysbusNMCGetWANStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSysbusNMCGetWANStatusParamsWithTimeout creates a new PostSysbusNMCGetWANStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSysbusNMCGetWANStatusParamsWithTimeout(timeout time.Duration) *PostSysbusNMCGetWANStatusParams {

	return &PostSysbusNMCGetWANStatusParams{

		timeout: timeout,
	}
}

// NewPostSysbusNMCGetWANStatusParamsWithContext creates a new PostSysbusNMCGetWANStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSysbusNMCGetWANStatusParamsWithContext(ctx context.Context) *PostSysbusNMCGetWANStatusParams {

	return &PostSysbusNMCGetWANStatusParams{

		Context: ctx,
	}
}

// NewPostSysbusNMCGetWANStatusParamsWithHTTPClient creates a new PostSysbusNMCGetWANStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSysbusNMCGetWANStatusParamsWithHTTPClient(client *http.Client) *PostSysbusNMCGetWANStatusParams {

	return &PostSysbusNMCGetWANStatusParams{
		HTTPClient: client,
	}
}

/*PostSysbusNMCGetWANStatusParams contains all the parameters to send to the API endpoint
for the post sysbus n m c get w a n status operation typically these are written to a http.Request
*/
type PostSysbusNMCGetWANStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) WithTimeout(timeout time.Duration) *PostSysbusNMCGetWANStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) WithContext(ctx context.Context) *PostSysbusNMCGetWANStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) WithHTTPClient(client *http.Client) *PostSysbusNMCGetWANStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sysbus n m c get w a n status params
func (o *PostSysbusNMCGetWANStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostSysbusNMCGetWANStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
