// Code generated by go-swagger; DO NOT EDIT.

package ip_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostSysbusNMCGetWANStatusReader is a Reader for the PostSysbusNMCGetWANStatus structure.
type PostSysbusNMCGetWANStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSysbusNMCGetWANStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSysbusNMCGetWANStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSysbusNMCGetWANStatusOK creates a PostSysbusNMCGetWANStatusOK with default headers values
func NewPostSysbusNMCGetWANStatusOK() *PostSysbusNMCGetWANStatusOK {
	return &PostSysbusNMCGetWANStatusOK{}
}

/*PostSysbusNMCGetWANStatusOK handles this case with default header values.

OK
*/
type PostSysbusNMCGetWANStatusOK struct {
	Payload *PostSysbusNMCGetWANStatusOKBody
}

func (o *PostSysbusNMCGetWANStatusOK) Error() string {
	return fmt.Sprintf("[POST /sysbus/NMC:getWANStatus][%d] postSysbusNMCGetWANStatusOK  %+v", 200, o.Payload)
}

func (o *PostSysbusNMCGetWANStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostSysbusNMCGetWANStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostSysbusNMCGetWANStatusOKBody post sysbus n m c get w a n status o k body
swagger:model PostSysbusNMCGetWANStatusOKBody
*/
type PostSysbusNMCGetWANStatusOKBody struct {

	// result
	Result *PostSysbusNMCGetWANStatusOKBodyResult `json:"result,omitempty"`
}

// Validate validates this post sysbus n m c get w a n status o k body
func (o *PostSysbusNMCGetWANStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostSysbusNMCGetWANStatusOKBody) validateResult(formats strfmt.Registry) error {

	if swag.IsZero(o.Result) { // not required
		return nil
	}

	if o.Result != nil {
		if err := o.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postSysbusNMCGetWANStatusOK" + "." + "result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBody) UnmarshalBinary(b []byte) error {
	var res PostSysbusNMCGetWANStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostSysbusNMCGetWANStatusOKBodyResult post sysbus n m c get w a n status o k body result
swagger:model PostSysbusNMCGetWANStatusOKBodyResult
*/
type PostSysbusNMCGetWANStatusOKBodyResult struct {

	// data
	Data *PostSysbusNMCGetWANStatusOKBodyResultData `json:"data,omitempty"`

	// status
	Status bool `json:"status,omitempty"`
}

// Validate validates this post sysbus n m c get w a n status o k body result
func (o *PostSysbusNMCGetWANStatusOKBodyResult) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostSysbusNMCGetWANStatusOKBodyResult) validateData(formats strfmt.Registry) error {

	if swag.IsZero(o.Data) { // not required
		return nil
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postSysbusNMCGetWANStatusOK" + "." + "result" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBodyResult) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBodyResult) UnmarshalBinary(b []byte) error {
	var res PostSysbusNMCGetWANStatusOKBodyResult
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostSysbusNMCGetWANStatusOKBodyResultData post sysbus n m c get w a n status o k body result data
swagger:model PostSysbusNMCGetWANStatusOKBodyResultData
*/
type PostSysbusNMCGetWANStatusOKBodyResultData struct {

	// connection state
	ConnectionState string `json:"ConnectionState,omitempty"`

	// DNS servers
	DNSServers string `json:"DNSServers,omitempty"`

	// IP address
	IPAddress string `json:"IPAddress,omitempty"`

	// ipv6 address
	IPV6Address string `json:"IPv6Address,omitempty"`

	// ipv6 delegated prefix
	IPV6DelegatedPrefix string `json:"IPv6DelegatedPrefix,omitempty"`

	// last connection error
	LastConnectionError string `json:"LastConnectionError,omitempty"`

	// link state
	LinkState string `json:"LinkState,omitempty"`

	// link type
	LinkType string `json:"LinkType,omitempty"`

	// m a c address
	MACAddress string `json:"MACAddress,omitempty"`

	// protocol
	Protocol string `json:"Protocol,omitempty"`

	// remote gateway
	RemoteGateway string `json:"RemoteGateway,omitempty"`

	// wan state
	WanState string `json:"WanState,omitempty"`
}

// Validate validates this post sysbus n m c get w a n status o k body result data
func (o *PostSysbusNMCGetWANStatusOKBodyResultData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBodyResultData) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSysbusNMCGetWANStatusOKBodyResultData) UnmarshalBinary(b []byte) error {
	var res PostSysbusNMCGetWANStatusOKBodyResultData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
